# Generated by Django 4.1.2 on 2022-10-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123, verbose_name='Название')),
                ('year', models.IntegerField(null=True)),
                ('author', models.CharField(max_length=50)),
                ('history', models.TextField(blank=True)),
                ('country', models.CharField(max_length=10)),
            ],
        ),
    ]
