# Generated by Django 4.1.2 on 2022-10-13 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='country',
        ),
    ]
